### ISSUE TITLE
Helper scripts to generate magic arrays

### ISSUE THREAD

**Issue by fsaintjacques** [lemire/streamvbyte#1]
Developers would benefit to know how those arrays are generated, mostly `shuffleTable`. Automating this stuff is also a good engineering practice.

**Comment by lemire** [comment]
I agree.

**Comment by KWillets** [comment]
I'm writing these to generate a magic encoder array, and I already did the decoder array to check my logic, so both will be covered.

**Comment by lemire** [comment]
As per @KWillets  PR, this is solved.
