### ISSUE TITLE
Unroll the encoder?

### ISSUE THREAD

**Issue by aqrit** [lemire/streamvbyte#20]
In the current version, empty space fills 75% of the xmm register, during some operations.
Unrolling 4x then packing ASAP, seems to get a ~9% improvement.

https://gist.github.com/aqrit/8fb615a05586d023e07cbd997cfcb6f9

food for thought.

**Comment by lemire** [comment]
Interesting.

**Comment by KWillets** [comment]
This was definitely on my list of things to try.

**Comment by lemire** [comment]
Anyone cares to prepare a pull request?

**Comment by aqrit** [comment]
[faster](https://gist.github.com/aqrit/746d2f5e4ad1909230e2283272333dc1#file-svb_thin-c-L108 )

Use `_mm_movemask_epi8` to extract key bits. (avoid multiplies and extracts)

**Comment by lemire** [comment]
@aqrit +1

To be assessed.

**Comment by KWillets** [comment]
I like it.  Multiply was kind of a brute-force solution.

**Comment by lemire** [comment]
Fixed as per https://github.com/lemire/streamvbyte/commit/efb310d51e82a76bf9f1353d052e441985916a97
