### ISSUE TITLE
Shared oibject version

### ISSUE THREAD

**Issue by outpaddling** [lemire/streamvbyte#40]
The cmake build is not producing libstreamvbyte.so.0.0.1, which I see is built by the mnimal Makefile.  Do you see the same on your end or is there maybe something amiss in my cmake configuration?

**Comment by lemire** [comment]
Please elaborate.

The README specifies the following...


> The cmake build system also offers a `libstreamvbyte_static.a` in addition to
`libstreamvbyte.so`.


I am closing this. If this does not answer your query, please provide a complete explanation in a new issue.

**Comment by lemire** [comment]
If you sync with our main branch and install the library, you will find that it create system libraries with version numbers.

**Comment by lemire** [comment]
(I mean: install it via a cmake build.)

**Comment by lemire** [comment]
> Do you see the same on your end or is there maybe something amiss in my cmake configuration?

To my knowledge, cmake does not produce a versioned file when building, it creates it at install time. It is the expected behaviour.

**Comment by outpaddling** [comment]
You are right, I should have noted that I was referring to the latest release.  I am using the cmake install target, BTW.

With the latest commit I see the following installed:

include/streamvbyte.h
include/streamvbyte_zigzag.h
include/streamvbytedelta.h
lib/libstreamvbyte.so
lib/libstreamvbyte.so.1
lib/libstreamvbyte.so.1.0.0
lib/libstreamvbyte_static.a

Thanks.

**Comment by lemire** [comment]
Thanks for your input.
