### ISSUE TITLE
Encoded size doesnt match decoded size.

### ISSUE THREAD

**Issue by THORCOMP** [lemire/streamvbyte#41]
Hey Guys,

A small code used to show the problem i m facing using streamvbytes library on linux

#include <stdint.h>
#include <streamvbyte.h>
#include <malloc.h>
#include <stdio.h>

int main( void )
{
size_t encoded = 0, decoded = 0;
uint8_t *set = malloc( 1024 );
uint32_t entry[ 2 ];

entry[ 0 ] = 10;
entry[ 1 ] = 0;

encoded += streamvbyte_encode( entry, 2, set );
for( size_t i = 0; i < 2; i++ ) {
decoded += streamvbyte_decode( set + decoded, entry, 1 );
}
printf( "encoded size : %zd vs decoded size : %zd\n", encoded, decoded );
free( set );

return 0;
}

When I run this code I got this output +1

encoded size : 3 vs decoded size : 4

Can you help me finding the issue ?

**Comment by lemire** [comment]
The documented usage is as follows:

```C++
// suppose that datain is an array of uint32_t integers
size_t compsize = streamvbyte_encode(datain, N, compressedbuffer); // encoding
// here the result is stored in compressedbuffer using compsize bytes
streamvbyte_decode(compressedbuffer, recovdata, N); // decoding (fast)
```

For each `streamvbyte_encode` call, you must have a matching `streamvbyte_decode` as illustrated in the example. Your code does not follow this pattern, you call `streamvbyte_encode` once and then you call `streamvbyte_decode` twice.

**Comment by THORCOMP** [comment]
Ok thanks a lot for your fast answer. It makes sense. Regards
