### ISSUE TITLE
Can this be built on Mac M1?

### ISSUE THREAD

**Issue by ChenZhongPu** [lemire/streamvbyte#60]
According to the README, Mac M1 is supported. 

> ... an ARM processor with NEON instructions ...

[Makefile](https://github.com/lemire/streamvbyte/blob/170fef1f1401960627d8a4dff08e54116de987db/Makefile#L8) uses `aarch64` as the condition for test:

```
ifeq ($(PROCESSOR), aarch64)
# for 64-bit ARM processors
CFLAGS = -fPIC -std=c99 -O3 -Wall -Wextra -pedantic -Wshadow -D__ARM_NEON__
```

But in fact what `uname -m` returns on my Mac M1 is `arm64`.  What about the following condition:

```
ifneq ($(filter $(PROCESSOR), arm64 aarch64),)
```

**Comment by lemire** [comment]
Thanks for the report.

I have had, myself, an M1, an M1 Pro and an M2 -based machine over the years. It has always worked. Apple defines `__ARM_NEON__` by default so there is no need to specify it.

Please reopen a new issue which provides, at a minimum, a detailed description of the build error you are encountering.
