### ISSUE TITLE
Multiple versions of streamvbyte

### ISSUE THREAD

**Issue by pps83** [lemire/streamvbyte#72]
What's the difference between https://github.com/lemire/streamvbyte and [streamvbyte implementation in FastPFor](https://github.com/lemire/FastPFor/blob/master/src/streamvbyte.c)? Shouldn't fastprof simply reference this one as a submodule instead of having its own implementation?

**Comment by lemire** [comment]
Can you describe the concrete problems that you are encountering in your applications, and how the refactoring you are proposing solves them?

**Comment by pps83** [comment]
I'm not facing any problems, I noticed that faspfor has separate implementation of streamvbyte and would like to know if these bit-exact (eg produce identical output), which one is more optimized etc.

**Comment by lemire** [comment]
I understand that you have not encountered an issue so I am going to close this issue.

If you'd like to investigate the code, add tests, benchmarks, benchmark results and so forth, you are invited to do so.
